-- Auto-generated seed for system_words (UI textos detectados en JS)
-- Solo se llena la columna en con el texto original encontrado; es/pt/fr quedan NULL

insert into public.system_words (word, en, es, pt, fr) values
('menu.login', 'Iniciar sesión', null, null, null),
('menu.register', 'Registrarse', null, null, null),
('menu.account', 'Mi cuenta', null, null, null),
('menu.signout', 'Cerrar sesión', null, null, null),
('menu.preferences', 'Preferencias', null, null, null),
('menu.notifications', 'Notificaciones', null, null, null),
('menu.menu', 'Menú', null, null, null),
('menu.users', 'Usuarios', null, null, null),
('menu.roles', 'Roles', null, null, null),
('menu.areas', 'Áreas', null, null, null),
('menu.languages', 'Languages', null, null, null),
('header.blessedPrefix', 'Bendecido ', null, null, null),
('header.creditsLabel', 'Créditos', null, null, null),
('header.stepsLabel', 'Escalones', null, null, null),
('header.floorLabel', 'Piso', null, null, null),

-- Login
('login.title', 'Iniciar sesión', null, null, null),
('login.identifierLabel', 'Usuario o correo', null, null, null),
('login.identifierPlaceholder', 'Usuario o correo', null, null, null),
('login.passwordLabel', 'Contraseña', null, null, null),
('login.passwordPlaceholder', 'Contraseña', null, null, null),
('login.btnCancel', 'Cancelar', null, null, null),
('login.submit', 'Iniciar sesión', null, null, null),
('login.forgotLink', '¿Olvidaste tu contraseña?', null, null, null),
('login.errorIdentifierRequired', 'Debes ingresar tu usuario o correo.', null, null, null),
('login.errorRequired', 'Debes ingresar tu usuario/correo y contraseña.', null, null, null),
('login.errorGeneric', 'No fue posible iniciar sesión. Verifica tus datos.', null, null, null),
('login.errorInvalidCredentials', 'Datos incorrectos.', null, null, null),
('login.identifierChecking', 'Buscando usuario.', null, null, null),
('login.identifierNotFound', 'No encontramos este usuario.', null, null, null),
('login.identifierError', 'No pudimos comprobar el usuario. Inténtalo de nuevo.', null, null, null),

-- Register
('register.title', 'Registrarse', null, null, null),
('register.emailLabel', 'Correo electrónico', null, null, null),
('register.passwordLabel', 'Contraseña', null, null, null),
('register.confirmPasswordLabel', 'Confirmar contraseña', null, null, null),
('register.btnCancel', 'Cancelar', null, null, null),
('register.submit', 'Registrarse', null, null, null),
('register.errorGeneric', 'No fue posible completar el registro. Intenta nuevamente.', null, null, null),
('register.success', 'Registro exitoso.', null, null, null),

-- Account
('account.title', 'Mi cuenta', null, null, null),
('account.save', 'Guardar', null, null, null),
('account.cancel', 'Cancelar', null, null, null),
('account.labels.username', 'Username', null, null, null),
('account.labels.email', 'Email', null, null, null),
('account.labels.firstName', 'First name', null, null, null),
('account.labels.lastName', 'Last name', null, null, null),
('account.labels.phone', 'Teléfono', null, null, null),
('account.labels.address', 'Dirección', null, null, null),
('account.labels.state', 'State', null, null, null),
('account.labels.zip', 'Código postal', null, null, null),
('account.labels.country', 'País', null, null, null),
('account.labels.birthDate', 'Fecha de nacimiento', null, null, null),
('account.labels.gender', 'Género', null, null, null),
('account.labels.notifications', 'Notificaciones', null, null, null),
('account.helper.username', 'Allowed characters: lowercase letters, numbers, dash (-) and underscore (_).', null, null, null),
('account.stats.credits', 'Créditos', null, null, null),
('account.stats.steps', 'Pasos', null, null, null),
('account.stats.xp', 'XP', null, null, null),
('account.stats.light', 'Luz', null, null, null),
('account.stats.roles', 'Roles', null, null, null),
('account.stats.views', 'Vistas', null, null, null),
('account.stats.likes', 'Me gusta', null, null, null),
('account.stats.notes', 'Notas', null, null, null),
('account.stats.shares', 'Compartidos', null, null, null),
('account.stats.notifications', 'Notificaciones', null, null, null),
('account.stats.history', 'Historial', null, null, null),

-- Users
('users.title', 'Usuarios', null, null, null),
('users.search.placeholder', 'Buscar usuarios', null, null, null),
('users.list.header.index', '#', null, null, null),
('users.list.header.name', 'Nombre', null, null, null),
('users.list.header.credits', 'Créditos', null, null, null),
('users.list.header.steps', 'Pasos', null, null, null),
('users.list.header.xp', 'XP', null, null, null),
('users.list.header.light', 'Luz', null, null, null),
('users.list.header.roles', 'Roles', null, null, null),
('users.list.header.views', 'Vistas', null, null, null),
('users.list.header.likes', 'Likes', null, null, null),
('users.list.header.notes', 'Notas', null, null, null),
('users.list.header.shares', 'Compartidos', null, null, null),
('users.list.header.notifications', 'Notificaciones', null, null, null),
('users.list.header.history', 'Historial', null, null, null),
('users.list.empty', 'No hay usuarios', null, null, null),
('users.list.edit', 'Editar', null, null, null),
('users.pagination.prev', 'Anterior', null, null, null),
('users.pagination.next', 'Siguiente', null, null, null),
('users.pagination.page', 'Página', null, null, null),
('users.perms.denied', 'No tienes permisos para Usuarios', null, null, null),

-- Roles
('roles.title', 'Roles', null, null, null),
('roles.search.placeholder', 'Buscar roles', null, null, null),
('roles.new', 'Nuevo rol', null, null, null),
('roles.list.name', 'Nombre', null, null, null),
('roles.list.parent', 'Superior', null, null, null),
('roles.list.activeCol', 'Activo', null, null, null),
('roles.list.defaultCol', 'Default', null, null, null),
('roles.list.actions', 'Acciones', null, null, null),
('roles.list.edit', 'Editar', null, null, null),
('roles.list.active', 'Activo', null, null, null),
('roles.list.inactive', 'Inactivo', null, null, null),
('roles.list.defaultYes', 'Sí', null, null, null),
('roles.list.defaultNo', 'No', null, null, null),
('roles.list.empty', 'No hay roles', null, null, null),
('roles.form.title.new', 'Nuevo rol', null, null, null),
('roles.form.title.edit', 'Editar rol', null, null, null),
('roles.form.name.en', 'Nombre (en)', null, null, null),
('roles.form.desc.en', 'Descripción (en)', null, null, null),
('roles.form.name.es', 'Nombre (es)', null, null, null),
('roles.form.desc.es', 'Descripción (es)', null, null, null),
('roles.form.parent', 'Superior', null, null, null),
('roles.form.active', 'Activo', null, null, null),
('roles.form.default', 'Default nuevos usuarios', null, null, null),
('roles.form.save', 'Guardar', null, null, null),
('roles.form.cancel', 'Cancelar', null, null, null),
('roles.msg.created', 'Rol creado correctamente', null, null, null),
('roles.msg.updated', 'Rol actualizado', null, null, null),
('roles.error.codeRequired', 'El código es obligatorio y no debe tener espacios', null, null, null),
('roles.error.nameRequired', 'El nombre es obligatorio', null, null, null),
('roles.error.parentCycle', 'El rol superior genera un ciclo', null, null, null),
('roles.error.toggle', 'No se pudo actualizar el estado del rol', null, null, null),
('roles.error.save', 'No se pudo guardar el rol', null, null, null),
('roles.error.cannotDeactivateMain', 'No puedes desactivar el rol principal', null, null, null),
('roles.perms.denied', 'No tienes permisos para Roles', null, null, null),

-- Areas
('areas.title', 'Áreas', null, null, null),
('areas.search.placeholder', 'Buscar áreas', null, null, null),
('areas.new', 'Nueva área', null, null, null),
('areas.list.name', 'Nombre', null, null, null),
('areas.list.source', 'Fuente', null, null, null),
('areas.list.owner', 'Rol dueño', null, null, null),
('areas.list.activeCol', 'Activo', null, null, null),
('areas.list.actions', 'Acciones', null, null, null),
('areas.list.edit', 'Editar', null, null, null),
('areas.list.active', 'Activo', null, null, null),
('areas.list.inactive', 'Inactivo', null, null, null),
('areas.list.empty', 'No hay áreas', null, null, null),
('areas.pagination.prev', 'Anterior', null, null, null),
('areas.pagination.next', 'Siguiente', null, null, null),
('areas.pagination.page', 'Página', null, null, null),
('areas.form.title.new', 'Nueva área', null, null, null),
('areas.form.title.edit', 'Editar área', null, null, null),
('areas.form.name.en', 'Nombre (en)', null, null, null),
('areas.form.desc.en', 'Descripción (en)', null, null, null),
('areas.form.name.es', 'Nombre (es)', null, null, null),
('areas.form.desc.es', 'Descripción (es)', null, null, null),
('areas.form.source', 'Fuente', null, null, null),
('areas.form.owner', 'Rol dueño', null, null, null),
('areas.form.active', 'Activo', null, null, null),
('areas.form.public', 'Pública', null, null, null),
('areas.form.save', 'Guardar', null, null, null),
('areas.form.cancel', 'Cancelar', null, null, null),
('areas.perms.title', 'Permisos por rol', null, null, null),
('areas.perms.role', 'Rol', null, null, null),
('areas.perms.view', 'Ver', null, null, null),
('areas.perms.participate', 'Participar', null, null, null),
('areas.perms.content', 'Contenido', null, null, null),
('areas.perms.members', 'Miembros', null, null, null),
('areas.perms.area', 'Área', null, null, null),
('areas.error.codeRequired', 'El código es obligatorio y sin espacios', null, null, null),
('areas.error.nameRequired', 'El nombre es obligatorio', null, null, null),
('areas.error.sourceRequired', 'Selecciona una fuente', null, null, null),
('areas.error.toggle', 'No se pudo actualizar el estado del área', null, null, null),
('areas.error.save', 'No se pudo guardar el área', null, null, null),
('areas.msg.created', 'Área creada correctamente', null, null, null),
('areas.msg.updated', 'Área actualizada', null, null, null),
('areas.perms.denied', 'No tienes permisos para áreas', null, null, null),

-- Languages admin
('languages.title', 'Languages / Idiomas', null, null, null),
('languages.select', 'Language:', null, null, null),
('languages.search.placeholder', 'Buscar por palabra o texto', null, null, null),
('languages.save', 'Guardar', null, null, null),
('languages.pagination.prev', 'Anterior', null, null, null),
('languages.pagination.next', 'Siguiente', null, null, null),
('languages.pagination.page', 'Página', null, null, null),
('languages.list.empty', 'No hay registros', null, null, null),
('languages.save.nothing', 'No hay cambios para guardar', null, null, null),
('languages.save.ok', 'Cambios guardados', null, null, null),
('languages.save.error', 'No se pudieron guardar los cambios', null, null, null),
('languages.perms.denied', 'No tienes permisos para idiomas', null, null, null),

-- Preferences / misc
('preferences.title', 'Preferencias', null, null, null),
('preferences.save', 'Guardar', null, null, null),
('preferences.cancel', 'Cancelar', null, null, null),

-- Genéricos
('common.edit', 'Editar', null, null, null),
('common.save', 'Guardar', null, null, null),
('common.cancel', 'Cancelar', null, null, null),
('common.search.placeholder', 'Buscar', null, null, null),
('common.table.empty', 'No hay registros', null, null, null),
('errors.generic', 'No fue posible completar la operación. Inténtalo nuevamente.', null, null, null)
on conflict (word) do update set en = excluded.en;

